package org.alpha.airline;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
public class TicketBooking {
 public static void main(String[]args) throws InterruptedException {
	   	System.setProperty("webdriver.chrome.driver","C:\\Pyro\\SeleniumProject\\Drivers\\chromedriver.exe");
		WebDriver  driver=new ChromeDriver();
		driver.get("https://www.alitalia.com/en_en/");
		driver.manage().window().maximize();
		driver.findElement(By.xpath("//span[text()='ACCEPT']")).click();
		WebElement ele=driver.findElement(By.linkText("BOOK"));
		ele.click();
		Thread.sleep(1000);
		WebElement radio = driver.findElement(By.xpath("(//span[@class='placeholder'])[5]"));
		radio.click();
		WebElement src=driver.findElement(By.xpath("(//input[@name='list_andata--prenota'])[1]"));
		src.click();
		src.sendKeys("London LON");	
		WebElement des=driver.findElement(By.xpath("(//*[@name=\"destination--prenota\"])[1]"));
		des.click();
		des.sendKeys("Rome FCO");
		WebElement date=driver.findElement(By.xpath("(//input[@class='date-input hasDatepicker'])[1]"));
		date.click();
		WebElement mth=driver.findElement(By.xpath("(//div[@class='ui-datepicker-title'])[1]"));
		mth.click();
		driver.findElement(By.xpath("//*[@id=\"ui-datepicker-div\"]/div[3]/table/tbody/tr[3]/td[3]/a")).click();
		WebElement search=driver.findElement(By.xpath("//span[@class='icon-ico-select-white']"));
		search.click();
		driver.findElement(By.xpath("//span[text()='Passengers']"));
		driver.findElement(By.id("addAdults")).click();
		driver.findElement(By.xpath("//label[@for='radio-business--prenota-mobile']")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("submitHidden--prenota")).click();
		Thread.sleep(15000);
		driver.findElement(By.xpath("//*[@id=\"booking-flight-select-selection\"]/div[10]/div[3]/div[3]/div[2]/div/div[6]/a[2]")).click();
		WebElement radio2=driver.findElement(By.xpath("(//a[@data-index-brand='4'])[3]"));
		Thread.sleep(2000);
		radio2.click();
		Thread.sleep(2000);
		WebElement choose=driver.findElement(By.xpath("//div[@class='bookingTable__rightButtonCover']"));
		choose.click();
		Thread.sleep(6000);
		WebElement nextbtn=driver.findElement(By.xpath("//*[@id=\"booking-flight-select-selection\"]/div[14]/a"));
		nextbtn.click();
		Thread.sleep(4000);
		driver.findElement(By.xpath("(//input[@autocomplete='given-name'])[1]")).sendKeys("Maha");
		driver.findElement(By.id("cognomeAdulto_1")).sendKeys("Chandran");
		driver.findElement(By.id("nomeAdulto_2")).sendKeys("Bava");
		driver.findElement(By.xpath("//input[@id='cognomeAdulto_2']")).sendKeys("Siva");
		driver.findElement(By.id("email")).sendKeys("MahaBava124567@gmail.com");
		WebElement prefix=driver.findElement(By.xpath("//select[@name='prefissoRecapito_1']"));
		prefix.click();
		Select sel1=new Select(prefix);
		sel1.selectByVisibleText("India (+91)");
		driver.findElement(By.xpath("//input[@id='valoreRecapito_1']")).sendKeys("9123456789");
		Thread.sleep(2000);	
		WebElement checkbox=driver.findElement(By.xpath("//span[text()='I agree to understand the ']"));
		checkbox.click();
		driver.findElement(By.id("datiPasseggeroSubmit")).click();
		Thread.sleep(8000);
		driver.findElement(By.xpath("(//span[text()='Next'])[2]")).click();
		Thread.sleep(8000);
		driver.findElement(By.id("card4-2-label")).click();
		WebElement cardnum=driver.findElement(By.id("numeroCarta"));
		cardnum.sendKeys("CNB3489567890");
		WebElement dte=driver.findElement(By.id("meseScadenza"));
		dte.sendKeys("22");
		WebElement year=driver.findElement(By.id("annoScadenza"));
		year.sendKeys("2020");
		WebElement cs=driver.findElement(By.id("cvc"));
		cs.sendKeys("345");
		WebElement custname=driver.findElement(By.id("nome"));
		custname.sendKeys("Maha");
		WebElement lstname=driver.findElement(By.id("cognome"));
		lstname.sendKeys("Chandran");
		driver.findElement(By.id("booking-acquista-cdc-submit")).click();
		
		}
	}